"""
Experimenter key management.

Keys are HMAC-signed tokens.  ``generate_key()`` creates a random payload
and appends a 12-hex-char HMAC tag so the server can later verify it issued
the key — without storing anything.  The deterministic ``owner_id``
(UUID-5) is derived from the full signed key so that studies and chains can
be associated with whoever holds the same key.

Set the ``EXPERIMENTER_KEY_SECRET`` environment variable in production.
A fallback is used for local development only.
"""

import hashlib
import hmac as _hmac
import os
import secrets
import uuid
from typing import Optional

from fastapi import APIRouter, Header, HTTPException, status

router = APIRouter(prefix="/experimenter", tags=["experimenter"])

# Namespace for UUID-5 derivation (arbitrary but fixed)
_NAMESPACE = uuid.UUID("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
_LOCAL_DEV_OWNER_ID = uuid.UUID("00000000-0000-0000-0000-000000000001")
_TRUTHY_ENV_VALUES = {"1", "true", "yes", "on"}
_PRODUCTION_ENV_VALUES = {"prod", "production"}

# ── HMAC key signing ────────────────────────────────────────────────────

def _get_signing_secret() -> bytes:
    """Return the HMAC signing secret, preferring the env var."""
    secret = os.getenv("EXPERIMENTER_KEY_SECRET", "")
    if not secret:
        if _is_production_environment() and not is_local_dev_bypass_auth_enabled():
            raise RuntimeError("EXPERIMENTER_KEY_SECRET is required in production")
        secret = "local-dev-signing-secret"  # safe only for localhost
    return secret.encode()


def _is_production_environment() -> bool:
    """Return True when the API is running in a hosted production environment."""
    candidates = (
        os.getenv("APP_ENV", ""),
        os.getenv("ENVIRONMENT", ""),
        os.getenv("RAILWAY_ENVIRONMENT", ""),
        os.getenv("VERCEL_ENV", ""),
    )
    return any(value.strip().lower() in _PRODUCTION_ENV_VALUES for value in candidates)


def _sign_payload(payload: str) -> str:
    """Return the first 12 hex chars of HMAC-SHA256(secret, payload)."""
    return _hmac.new(
        _get_signing_secret(), payload.encode(), hashlib.sha256
    ).hexdigest()[:12]


def _make_signed_key() -> str:
    """Generate a random payload and return ``payload.signature``."""
    payload = secrets.token_urlsafe(24)  # 32-char URL-safe random part
    sig = _sign_payload(payload)
    return f"{payload}.{sig}"


def is_valid_signed_key(key: str) -> bool:
    """Return True when *key* carries a valid HMAC signature."""
    key = key.strip()
    dot = key.rfind(".")
    if dot == -1:
        return False
    payload, sig = key[:dot], key[dot + 1:]
    expected = _sign_payload(payload)
    return _hmac.compare_digest(sig, expected)


# ── helpers ──────────────────────────────────────────────────────────────

def owner_id_from_key(key: str) -> uuid.UUID:
    """Deterministic owner_id from an experimenter key."""
    return uuid.uuid5(_NAMESPACE, key.strip())


def is_local_dev_bypass_auth_enabled() -> bool:
    """Return True when key auth is disabled for local development."""
    value = os.getenv("LOCAL_DEV_BYPASS_AUTH", "")
    return value.strip().lower() in _TRUTHY_ENV_VALUES


def local_dev_owner_id() -> uuid.UUID:
    """Stable owner_id used when LOCAL_DEV_BYPASS_AUTH is enabled."""
    return _LOCAL_DEV_OWNER_ID


def _validate_and_resolve(key: str) -> uuid.UUID:
    """Validate an experimenter key and return the derived owner_id.

    Raises 401 if the key was not generated by this server.
    """
    if not is_valid_signed_key(key):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid experimenter key",
        )
    return owner_id_from_key(key)


# ── FastAPI dependencies ─────────────────────────────────────────────────

def get_optional_owner(
    x_experimenter_key: Optional[str] = Header(default=None, alias="x-experimenter-key"),
) -> Optional[uuid.UUID]:
    """FastAPI dependency — returns owner_id when a key header is present."""
    if x_experimenter_key and x_experimenter_key.strip():
        return _validate_and_resolve(x_experimenter_key)
    if is_local_dev_bypass_auth_enabled():
        return local_dev_owner_id()
    return None


def get_required_owner(
    x_experimenter_key: Optional[str] = Header(default=None, alias="x-experimenter-key"),
) -> uuid.UUID:
    """FastAPI dependency — requires an experimenter key and returns owner_id."""
    if x_experimenter_key and x_experimenter_key.strip():
        return _validate_and_resolve(x_experimenter_key)
    if is_local_dev_bypass_auth_enabled():
        return local_dev_owner_id()
    raise HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Provide an x-experimenter-key header",
    )


# ── routes ───────────────────────────────────────────────────────────────

@router.post("/generate-key")
async def generate_key():
    """Generate a new HMAC-signed experimenter key.

    The key is **not** stored on the server.  The caller must save it.
    The server can verify it issued the key via the embedded signature.
    """
    key = _make_signed_key()
    return {"key": key}
